# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "jstanislawczyk-terraform-state"
    encrypt = true
    key     = "common/terraform.tfstate"
    region  = "us-east-1"
  }
}
